---

- name: firewall > iptables in CentOS 6
  block:
    - name: iptable rules for PostgreSQL port
      iptables:
        chain: INPUT
        protocol: "{{ ip_rule.protocol }}"
        destination_port: "{{ ip_rule.port }}"
        jump: ACCEPT
        action: insert
      register: iptables_conf_edit
      with_items:
        - port: 9999
          protocol: tcp
        - port: 9898
          protocol: tcp
        - port: 9000
          protocol: tcp
        - port: 9694
          protocol: udp
      loop_control:
        loop_var: ip_rule

    - name: Save iptables rules
      command: service iptables save
      when: iptables_conf_edit is changed

  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: firewall > firewalld in CentOS 7
  block:
    - name: Ensure firewalld is running
      systemd:
        name: firewalld
        state: started
        enabled: true

    - name: firewalld rule for PGPool-II ports
      firewalld:
        port: "{{ firewall_port }}"
        permanent: true
        state: enabled
      register: firewall_conf_edit
      with_items: ["9999/tcp", "9898/tcp", "9000/tcp", "9694/udp"]
      loop_control:
        loop_var: firewall_port

    - name: Reload firewalld rules
      command: firewall-cmd --reload
      when: firewall_conf_edit is changed

  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

